# dependabot.yml file with updates
# https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates

version: 2
updates:
    # Configuration for npm
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "monthly"
