scss_files: _sass/**/*.scss

exclude:
    - _sass/tool.debug.scss
    - _sass/component.syntax.scss

linters:
  PropertySortOrder:
    order: smacss
  Indentation:
    width: 4;
  TrailingWhitespace:
    enabled: false
  ColorVariable:
    enabled: false
